/**
 * ─────────────────────────────────────────────────────────────────────────────
 * WorkerBridge — Integration Plan (No Main-Thread Blocking)
 * Part of: HybridRuntime → OfflineMediaEngine
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Problem:
 *   All three sub-modules (AudioPipeline, KnowledgeStore, LocalAILoader)
 *   perform heavy computation (embedding, tokenisation, inference).
 *   Running them on the main thread would freeze the React UI during inference.
 *
 * Solution — Three-Layer Architecture:
 *
 *   ┌─────────────────────────────────────────────────────────────┐
 *   │  React UI (Main Thread)                                     │
 *   │  useOfflineMediaEngine() hook                               │
 *   │  → sends typed messages, receives streamed results via      │
 *   │    transferable objects (no serialisation overhead)         │
 *   └───────────────────────┬─────────────────────────────────────┘
 *                           │  postMessage / onmessage
 *                           │  (structured clone + Transferable)
 *   ┌───────────────────────▼─────────────────────────────────────┐
 *   │  OfflineMediaWorker (Dedicated Web Worker)                  │
 *   │  • Owns AudioPipeline, KnowledgeStore, LocalAILoader        │
 *   │  • Uses WebGPU / IndexedDB / SubtleCrypto directly          │
 *   │    (all available inside workers)                           │
 *   │  • Routes incoming WorkerRequest → correct sub-module       │
 *   │  • Streams back WorkerResponse events token-by-token        │
 *   └─────────────────────────────────────────────────────────────┘
 *
 * Message protocol is typed and versioned to enable safe upgrades.
 * ─────────────────────────────────────────────────────────────────────────────
 */

/* ── Request message types ─────────────────────────────────────────────── */

export type WorkerRequestType =
  | "init"
  | "tts:speak"
  | "tts:stop"
  | "tts:pause"
  | "tts:resume"
  | "ks:ingestBook"
  | "ks:search"
  | "ks:getChunks"
  | "ks:deleteBook"
  | "ai:loadModel"
  | "ai:chat"
  | "ai:chatStream"
  | "ai:clearHistory"
  | "ai:evictModel"
  | "crypto:encrypt"
  | "crypto:decrypt"
  | "vision:analyzeFrame";

/** Base shape — every request carries a correlation ID for response matching. */
export interface WorkerRequestBase {
  /** UUID generated by the UI side. Used to match responses. */
  requestId: string;
  type:      WorkerRequestType;
}

/* Individual request payloads */

export interface InitRequest extends WorkerRequestBase {
  type:        "init";
  forceBackend?: "webgpu" | "webgl2" | "wasm-cpu";
}

export interface TTSSpeakRequest extends WorkerRequestBase {
  type:     "tts:speak";
  text:     string;
  rate?:    number;
  pitch?:   number;
  volume?:  number;
  voiceId?: string;
}

export interface KSIngestRequest extends WorkerRequestBase {
  type:       "ks:ingestBook";
  bookId:     string;
  title:      string;
  subject:    string;
  author:     string;
  chapters:   Array<{ title: string; text: string }>;
}

export interface KSSearchRequest extends WorkerRequestBase {
  type:    "ks:search";
  query:   string;
  topK?:   number;
}

export interface AILoadModelRequest extends WorkerRequestBase {
  type:        "ai:loadModel";
  manifestId:  string;
  /** Transfer the model bytes to the worker — zero-copy. */
  modelBuffer?: ArrayBuffer;
}

export interface AIChatRequest extends WorkerRequestBase {
  type:        "ai:chat";
  sessionId:   string;
  message:     string;
  /** Whether to stream tokens back (triggers AIChatStreamResponse). */
  stream:      boolean;
  useRAG?:     boolean;
}

export interface CryptoEncryptRequest extends WorkerRequestBase {
  type:      "crypto:encrypt";
  plaintext: string;
}

export interface CryptoDecryptRequest extends WorkerRequestBase {
  type:  "crypto:decrypt";
  iv:    string;
  data:  string;
  keyId: string;
}

export interface VisionAnalyzeFrameRequest extends WorkerRequestBase {
  type:        "vision:analyzeFrame";
  sessionId:   string;
  imageBase64: string;
  question:    string;
  subject?:    string;
  language?:   "ar" | "en";
  useRAG?:     boolean;
  stream?:     boolean;
}

/** Union of all request types */
export type WorkerRequest =
  | InitRequest
  | TTSSpeakRequest
  | KSIngestRequest
  | KSSearchRequest
  | AILoadModelRequest
  | AIChatRequest
  | CryptoEncryptRequest
  | CryptoDecryptRequest
  | VisionAnalyzeFrameRequest;

/* ── Response message types ────────────────────────────────────────────── */

export type WorkerResponseStatus = "ok" | "error" | "stream" | "progress";

/** Generic error response — always included in the union */
export interface WorkerErrorResponse {
  requestId: string;
  status:    "error";
  error:     string;
}

export interface WorkerResponseBase {
  requestId: string;
  status:    WorkerResponseStatus;
  error?:    string;
}

export interface InitResponse extends WorkerResponseBase {
  status:   "ok";
  backend:  string;
  ttsReady: boolean;
  idbReady: boolean;
  aiReady:  boolean;
}

export interface TTSWordEvent extends WorkerResponseBase {
  status:     "stream";
  event:      "word";
  word:       string;
  charIndex:  number;
}

export interface TTSDoneEvent extends WorkerResponseBase {
  status: "ok";
  event:  "done";
}

export interface KSSearchResponse extends WorkerResponseBase {
  status:  "ok";
  results: Array<{
    chunkId:  string;
    bookId:   string;
    text:     string;
    score:    number;
    highlight:string;
  }>;
}

export interface AITokenEvent extends WorkerResponseBase {
  status:     "stream";
  token:      string;
  isFinished: boolean;
}

export interface AIChatResponse extends WorkerResponseBase {
  status:         "ok";
  fullText:       string;
  tokensPerSecond: number;
}

export interface LoadProgressResponse extends WorkerResponseBase {
  status:    "progress";
  phase:     string;
  pct:       number;
  message:   string;
}

export interface CryptoResponse extends WorkerResponseBase {
  status: "ok";
  result: string;
}

export interface VisionAnalyzeFrameResponse extends WorkerResponseBase {
  status:   "ok";
  fullText: string;
  ragUsed:  boolean;
}

/** Union of all response types */
export type WorkerResponse =
  | InitResponse
  | TTSWordEvent
  | TTSDoneEvent
  | KSSearchResponse
  | AITokenEvent
  | AIChatResponse
  | LoadProgressResponse
  | CryptoResponse
  | VisionAnalyzeFrameResponse
  | WorkerErrorResponse;

/* ── Worker-side dispatcher skeleton ──────────────────────────────────── */

/**
 * IWorkerDispatcher
 * -----------------
 * Implemented inside `offline-media.worker.ts` (runs in the Worker context).
 * Never imported by the main-thread code — only WorkerBridge talks to it.
 */
export interface IWorkerDispatcher {
  /** Called by the worker's `onmessage` handler. */
  dispatch(request: WorkerRequest): Promise<void>;

  /** Emit a response back to the main thread. */
  emit(response: WorkerResponse, transfer?: Transferable[]): void;
}

/**
 * OfflineMediaWorkerDispatcher (skeleton)
 * ----------------------------------------
 * The concrete class lives in the worker file.
 * It holds references to AudioPipeline, KnowledgeStore, LocalAILoader.
 */
export abstract class OfflineMediaWorkerDispatcher implements IWorkerDispatcher {
  abstract dispatch(request: WorkerRequest): Promise<void>;
  abstract emit(response: WorkerResponse, transfer?: Transferable[]): void;

  protected abstract handleInit(req: InitRequest): Promise<void>;
  protected abstract handleTTSSpeak(req: TTSSpeakRequest): Promise<void>;
  protected abstract handleKSSearch(req: KSSearchRequest): Promise<void>;
  protected abstract handleAIChat(req: AIChatRequest): Promise<void>;
  protected abstract handleCryptoEncrypt(req: CryptoEncryptRequest): Promise<void>;
}

/* ── Main-thread WorkerBridge ──────────────────────────────────────────── */

export type ResponseHandler = (response: WorkerResponse) => void;

export interface WorkerBridgeConfig {
  /** Path to the compiled worker file. */
  workerUrl:   string;
  /** Timeout for responses that are not streams (ms). Default 30 000. */
  timeout?:    number;
}

/**
 * IWorkerBridge
 * -------------
 * The main-thread proxy. React components and hooks use this exclusively.
 * It manages the Worker lifecycle and demultiplexes responses by requestId.
 *
 * Usage:
 *   const bridge = new WorkerBridge({ workerUrl: "/workers/offline-media.js" });
 *   await bridge.init();
 *   const results = await bridge.search("قانون الجاذبية");
 *   bridge.speak("النص المراد قراءته", { onWord: w => setWord(w) });
 */
export interface IWorkerBridge {
  readonly isReady: boolean;

  /** Spawn the Worker and await its InitResponse. */
  init(opts?: { forceBackend?: "webgpu" | "webgl2" | "wasm-cpu" }): Promise<InitResponse>;

  /* TTS */
  speak(
    text:    string,
    opts?:   { rate?: number; onWord?: (w: string) => void; onEnd?: () => void }
  ): Promise<void>;
  stopTTS():   void;
  pauseTTS():  void;
  resumeTTS(): void;

  /* Knowledge Store */
  ingestBook(
    descriptor: { bookId: string; title: string; subject: string; author: string },
    chapters:   Array<{ title: string; text: string }>,
  ): Promise<void>;
  search(query: string, topK?: number): Promise<KSSearchResponse["results"]>;

  /* AI */
  loadModel(manifestId: string): Promise<void>;
  chat(
    sessionId:  string,
    message:    string,
    opts?:      { stream?: boolean; onToken?: (token: string) => void; useRAG?: boolean },
  ): Promise<string>;

  /* Crypto */
  encrypt(plaintext: string): Promise<string>;
  decrypt(blob: { iv: string; data: string; keyId: string }): Promise<string>;

  /* Vision */
  analyzeFrame(
    imageBase64: string,
    question:    string,
    opts?: {
      sessionId?: string;
      subject?:   string;
      language?:  "ar" | "en";
      useRAG?:    boolean;
      stream?:    boolean;
      onToken?:   (token: string) => void;
    },
  ): Promise<string>;

  /** Tear down the Worker. */
  terminate(): void;
}

/** Concrete skeleton */
export abstract class WorkerBridge implements IWorkerBridge {
  protected worker: Worker | null = null;

  /** Pending response handlers keyed by requestId. */
  protected pending = new Map<string, ResponseHandler>();

  constructor(protected readonly config: WorkerBridgeConfig) {}

  abstract readonly isReady: boolean;

  abstract init(opts?: { forceBackend?: "webgpu" | "webgl2" | "wasm-cpu" }): Promise<InitResponse>;
  abstract speak(text: string, opts?: { rate?: number; onWord?: (w: string) => void; onEnd?: () => void }): Promise<void>;
  abstract stopTTS():   void;
  abstract pauseTTS():  void;
  abstract resumeTTS(): void;
  abstract ingestBook(descriptor: { bookId: string; title: string; subject: string; author: string }, chapters: Array<{ title: string; text: string }>): Promise<void>;
  abstract search(query: string, topK?: number): Promise<KSSearchResponse["results"]>;
  abstract loadModel(manifestId: string): Promise<void>;
  abstract chat(sessionId: string, message: string, opts?: { stream?: boolean; onToken?: (token: string) => void; useRAG?: boolean }): Promise<string>;
  abstract encrypt(plaintext: string): Promise<string>;
  abstract decrypt(blob: { iv: string; data: string; keyId: string }): Promise<string>;
  abstract analyzeFrame(
    imageBase64: string,
    question:    string,
    opts?: {
      sessionId?: string;
      subject?:   string;
      language?:  "ar" | "en";
      useRAG?:    boolean;
      stream?:    boolean;
      onToken?:   (token: string) => void;
    },
  ): Promise<string>;
  abstract terminate(): void;

  /** Generate a request correlation ID. */
  protected newId(): string {
    return `req_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  }

  /** Send a request and register its handler. */
  protected send(request: WorkerRequest, transfer?: Transferable[]): void {
    if (!this.worker) throw new Error("Worker not initialised");
    this.worker.postMessage(request, transfer ?? []);
  }
}
